-- Tworzenie tabeli UŻYTKOWNIK
CREATE TABLE PUBLIC.UŻYTKOWNIK (
    ID INTEGER PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    HASLO VARCHAR(255) NOT NULL,
    DATA_UTWORZENIA DATE,
    BIO VARCHAR(255),
    UNIQUE(LOGIN),
    UNIQUE(EMAIL)
);

-- Tworzenie tabeli WPIS
CREATE TABLE PUBLIC.WPIS (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    TRESC VARCHAR(280) NOT NULL,
    DATA_DODANIA TIMESTAMP NOT NULL,
    LICZBA_LAJKOW INTEGER,
    CONSTRAINT FK_WPIS_USER FOREIGN KEY(USER_ID) REFERENCES PUBLIC.UŻYTKOWNIK(ID)
);

-- Tworzenie tabeli FOLLOWER
CREATE TABLE PUBLIC.FOLLOWER (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    FOLLOWER_ID INTEGER NOT NULL,
    FOLLOWING_ID INTEGER NOT NULL,
    DATA_OBSERWACJI DATE NOT NULL,
    CONSTRAINT FK_FOLLOWER_OBSERWUJACY FOREIGN KEY(FOLLOWER_ID) REFERENCES PUBLIC.UŻYTKOWNIK(ID),
    CONSTRAINT FK_FOLLOWER_OBSERWOWANY FOREIGN KEY(FOLLOWING_ID) REFERENCES PUBLIC.UŻYTKOWNIK(ID),
    CONSTRAINT CHK_FOLLOWER_NOT_SELF CHECK(FOLLOWER_ID != FOLLOWING_ID)
);