-- Tworzenie tabeli UZYTKOWNIK
CREATE TABLE PUBLIC.UZYTKOWNIK (
    ID INTEGER PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    HASLO VARCHAR(255) NOT NULL,
    DATA_UTWORZENIA DATE,
    BIO VARCHAR(255),
    UNIQUE(LOGIN),
    UNIQUE(EMAIL)
);

-- Tworzenie tabeli WPIS
CREATE TABLE PUBLIC.WPIS (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    TRESC VARCHAR(280) NOT NULL,
    DATA_DODANIA TIMESTAMP NOT NULL,
    LICZBA_LAJKOW INTEGER,
    CONSTRAINT FK_WPIS_USER FOREIGN KEY(USER_ID) REFERENCES PUBLIC.UZYTKOWNIK(ID)
);

-- Tworzenie tabeli FOLLOWER
CREATE TABLE PUBLIC.FOLLOWER (
    ID INTEGER PRIMARY KEY,
    FOLLOWER_ID INTEGER NOT NULL,
    FOLLOWEE_ID INTEGER NOT NULL,
    DATA_OBSERWACJI DATE NOT NULL,
    CONSTRAINT FK_FOLLOWER_OBSERWUJACY FOREIGN KEY(FOLLOWER_ID) REFERENCES PUBLIC.UZYTKOWNIK(ID),
    CONSTRAINT FK_FOLLOWER_OBSERWOWANY FOREIGN KEY(FOLLOWEE_ID) REFERENCES PUBLIC.UZYTKOWNIK(ID),
    CONSTRAINT CHK_FOLLOWER_NOT_SELF CHECK(FOLLOWER_ID != FOLLOWEE_ID)
);
